
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 100 AND 105;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN(151 , 152, 153, 154 , 155);
SELECT * FROM EMPLOYEES WHERE first_name LIKE 'P%' OR  first_name LIKE  'p%';
SELECT * FROM EMPLOYEES WHERE first_name LIKE '%A' OR  first_name LIKE  '%a';
SELECT * FROM EMPLOYEES WHERE first_name LIKE '%A%' OR  first_name LIKE  '%a%';
SELECT * FROM EMPLOYEES WHERE first_name LIKE '__E%' OR  first_name LIKE  '__e%';
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL;
INSERT INTO  EMPLOYEES
(EMPLOYEE_ID ,FIRST_NAME ,LAST_NAME ,HIRE_DATE ,EMAIL,JOB_ID,MANAGER_ID )
VALUES (1,'SHEHAB','EMAM',SYSDATE ,'SHEHABEMAM','FI_ACCOUNT',NULL);
 



SELECT * FROM EMPLOYEES WHERE JOB_ID ='AD_VP' OR JOB_ID ='IT_PROG' ;

SELECT * FROM EMPLOYEES  ORDER BY last_name ASC ;
SELECT * FROM EMPLOYEES  ORDER BY hire_date  DESC ;


SELECT * FROM EMPLOYEES  ORDER BY DEPARTMENT_ID  ASC ,SALARY DESC ;

SELECT LOWER(last_name) FROM EMPLOYEES ;
SELECT UPPER (first_name ) FROM EMPLOYEES ;
SELECT INITCAP (first_name), INITCAP(LAST_NAME) FROM EMPLOYEES ;

SELECT * FROM EMPLOYEES WHERE LOWER(last_name) = 'smith' ;







